#!/bin/sh

# This script installs the Nix package manager on your system by
# downloading a binary distribution and running its installer script
# (which in turn creates and populates /nix).

{ # Prevent execution if this script was only partially downloaded
oops() {
    echo "$0:" "$@" >&2
    exit 1
}

umask 0022

tmpDir="$(mktemp -d -t nix-binary-tarball-unpack.XXXXXXXXXX || \
          oops "Can't create temporary directory for downloading the Nix binary tarball")"
cleanup() {
    rm -rf "$tmpDir"
}
trap cleanup EXIT INT QUIT TERM

require_util() {
    command -v "$1" > /dev/null 2>&1 ||
        oops "you do not have '$1' installed, which I need to $2"
}

case "$(uname -s).$(uname -m)" in
    Linux.x86_64)
        hash=b6505e3930caa0c48d37604762a1c457afcb3f035ae611002a995a6e15c7b059
        path=ryc8pfra2m0zv89gfnqrihda1n3yf9im/nix-2.12.0-x86_64-linux.tar.xz
        system=x86_64-linux
        ;;
    Linux.i?86)
        hash=5a80459e6c8359d4f3bbbf5b0617ef605c9d87d7ecbc9db7ebeddafed248e3c1
        path=jsp4b848xnnsj0hib9qnqgjcy8yc7b7q/nix-2.12.0-i686-linux.tar.xz
        system=i686-linux
        ;;
    Linux.aarch64)
        hash=38b2ce34fe9329f0aee8396a0b15bcf6639311e780929363650254186f15607c
        path=rfpka58ygihq8hyjd8yym8y7wyjlmgzh/nix-2.12.0-aarch64-linux.tar.xz
        system=aarch64-linux
        ;;
    Linux.armv6l)
        hash=7da96934a2729cc1fa567762a2afa99f4343011254e22e288a46707b29bc8f75
        path=995ib3qzzam7y7awls1ia6pngkiakp2q/nix-2.12.0-armv6l-linux.tar.xz
        system=armv6l-linux
        ;;
    Linux.armv7l)
        hash=d64090c82a76c14633ed83383f0039ed82a9cba4f7cc5134efdfc890226ba91d
        path=0kyrlcpqnzgqn926n0r1fn9v13pz81kl/nix-2.12.0-armv7l-linux.tar.xz
        system=armv7l-linux
        ;;
    Darwin.x86_64)
        hash=bb587f4c2b3d6fcd7bac8e46640e1a4a886831ceb87806a72fdca964a6693c80
        path=ciyms25f240md7daijj74yfrmphhv6xk/nix-2.12.0-x86_64-darwin.tar.xz
        system=x86_64-darwin
        ;;
    Darwin.arm64|Darwin.aarch64)
        hash=82b3541514c81237a2427d491a5a9d9a423e162eee40414d4bdb9e548e3ddefa
        path=zca9szkldzqs3gj94k6r9z6g7kdwxhvf/nix-2.12.0-aarch64-darwin.tar.xz
        system=aarch64-darwin
        ;;
    *) oops "sorry, there is no binary distribution of Nix for your platform";;
esac

# Use this command-line option to fetch the tarballs using nar-serve or Cachix
if [ "${1:-}" = "--tarball-url-prefix" ]; then
    if [ -z "${2:-}" ]; then
        oops "missing argument for --tarball-url-prefix"
    fi
    url=${2}/${path}
    shift 2
else
    url=https://releases.nixos.org/nix/nix-2.12.0/nix-2.12.0-$system.tar.xz
fi

tarball=$tmpDir/nix-2.12.0-$system.tar.xz

require_util tar "unpack the binary tarball"
if [ "$(uname -s)" != "Darwin" ]; then
    require_util xz "unpack the binary tarball"
fi

if command -v curl > /dev/null 2>&1; then
    fetch() { curl --fail -L "$1" -o "$2"; }
elif command -v wget > /dev/null 2>&1; then
    fetch() { wget "$1" -O "$2"; }
else
    oops "you don't have wget or curl installed, which I need to download the binary tarball"
fi

echo "downloading Nix 2.12.0 binary tarball for $system from '$url' to '$tmpDir'..."
fetch "$url" "$tarball" || oops "failed to download '$url'"

if command -v sha256sum > /dev/null 2>&1; then
    hash2="$(sha256sum -b "$tarball" | cut -c1-64)"
elif command -v shasum > /dev/null 2>&1; then
    hash2="$(shasum -a 256 -b "$tarball" | cut -c1-64)"
elif command -v openssl > /dev/null 2>&1; then
    hash2="$(openssl dgst -r -sha256 "$tarball" | cut -c1-64)"
else
    oops "cannot verify the SHA-256 hash of '$url'; you need one of 'shasum', 'sha256sum', or 'openssl'"
fi

if [ "$hash" != "$hash2" ]; then
    oops "SHA-256 hash mismatch in '$url'; expected $hash, got $hash2"
fi

unpack=$tmpDir/unpack
mkdir -p "$unpack"
tar -xJf "$tarball" -C "$unpack" || oops "failed to unpack '$url'"

script=$(echo "$unpack"/*/install)

[ -e "$script" ] || oops "installation script is missing from the binary tarball!"
export INVOKED_FROM_INSTALL_IN=1
"$script" "$@"

} # End of wrapping
